name: Deploy Backend
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Run Database Migrations
        run: |
          cd backend
          npx knex migrate:latest

      - name: Start Backend Server
        run: |
          cd backend
          npm start
